export const AUTHENTICATE = "AUTHENTICATE";
export type AUTHENTICATE = typeof AUTHENTICATE;

export const UNAUTHENTICATE = "UNAUTHENTICATE";
export type UNAUTHENTICATE = typeof UNAUTHENTICATE;

export const GETGLOBALDATA = "GETGLOBALDATA";
export type GETGLOBALDATA = typeof GETGLOBALDATA;

export const GETGLOBALDATAERROR = "GETGLOBALDATAERROR";
export type GETGLOBALDATAERROR = typeof GETGLOBALDATAERROR;
